[workspace]
members = [
    "minesweeper",
    "app",
    "web",
]
resolver = "1"

[workspace.dependencies]
egui = { version = "0.22.0", features = ["persistence"] }
eframe = { version = "0.22.0", features = ["persistence"] }

[profile.release]
strip = true
